export interface FormField {
  label: string;
  type: 'text' | 'date' | 'time' | 'signature' | 'checkbox' | 'textarea' | 'select' | 'photo';
  required?: boolean;
  options?: string[];
  width?: 'full' | 'half';
  maxPhotos?: number;
}

export const defaultFormFields: Record<string, FormField[]> = {
  '1': [ // Key Access Log
    { label: 'Date', type: 'date', required: true, width: 'half' },
    { label: 'Time', type: 'time', required: true, width: 'half' },
    { label: 'Key ID / Number', type: 'text', required: true, width: 'half' },
    { label: 'Key Description', type: 'text', required: true, width: 'half' },
    { label: 'Issued To (Name)', type: 'text', required: true },
    { label: 'Company / Department', type: 'text', width: 'half' },
    { label: 'Contact Number', type: 'text', width: 'half' },
    { label: 'Purpose of Issue', type: 'textarea', required: true },
    { label: 'Issue Time', type: 'time', required: true, width: 'half' },
    { label: 'Return Time', type: 'time', width: 'half' },
    { label: 'Supporting Photos', type: 'photo', maxPhotos: 3 },
    { label: 'Recipient Signature', type: 'signature', required: true },
    { label: 'Issuing Officer Signature', type: 'signature', required: true },
    { label: 'Notes / Remarks', type: 'textarea' },
  ],
  '2': [ // Roof Access Journal
    { label: 'Date', type: 'date', required: true, width: 'half' },
    { label: 'Permit Number', type: 'text', width: 'half' },
    { label: 'Personnel Name', type: 'text', required: true },
    { label: 'Company', type: 'text', required: true, width: 'half' },
    { label: 'ID Number', type: 'text', width: 'half' },
    { label: 'Time In', type: 'time', required: true, width: 'half' },
    { label: 'Time Out', type: 'time', width: 'half' },
    { label: 'Reason for Access', type: 'textarea', required: true },
    { label: 'Equipment Carried', type: 'textarea' },
    { label: 'Safety Briefing Completed', type: 'checkbox', required: true },
    { label: 'PPE Worn', type: 'checkbox', required: true },
    { label: 'Supporting Photos', type: 'photo', maxPhotos: 5 },
    { label: 'Authorised By', type: 'text', required: true },
    { label: 'Authoriser Signature', type: 'signature', required: true },
    { label: 'Personnel Signature', type: 'signature', required: true },
  ],
  '3': [ // Daily Site Handover Log
    { label: 'Date', type: 'date', required: true, width: 'half' },
    { label: 'Shift', type: 'select', options: ['Day Shift', 'Night Shift'], required: true, width: 'half' },
    { label: 'Outgoing Officer Name', type: 'text', required: true, width: 'half' },
    { label: 'Incoming Officer Name', type: 'text', required: true, width: 'half' },
    { label: 'Handover Time', type: 'time', required: true },
    { label: 'Outstanding Tasks', type: 'textarea', required: true },
    { label: 'Incidents During Shift', type: 'textarea' },
    { label: 'Equipment Status', type: 'textarea' },
    { label: 'Key Items Handed Over', type: 'textarea' },
    { label: 'Special Instructions', type: 'textarea' },
    { label: 'Supporting Photos', type: 'photo', maxPhotos: 5 },
    { label: 'Outgoing Officer Signature', type: 'signature', required: true },
    { label: 'Incoming Officer Signature', type: 'signature', required: true },
  ],
  '4': [ // Asset Inspection Report
    { label: 'Date', type: 'date', required: true, width: 'half' },
    { label: 'Asset ID', type: 'text', required: true, width: 'half' },
    { label: 'Asset Type', type: 'select', options: ['HVAC', 'Lift', 'Escalator', 'Generator', 'Fire System', 'Other'], required: true },
    { label: 'Location', type: 'text', required: true },
    { label: 'Inspector Name', type: 'text', required: true },
    { label: 'Visual Condition', type: 'select', options: ['Good', 'Fair', 'Poor', 'Critical'], required: true, width: 'half' },
    { label: 'Operational Status', type: 'select', options: ['Operational', 'Degraded', 'Non-Operational'], required: true, width: 'half' },
    { label: 'Last Service Date', type: 'date', width: 'half' },
    { label: 'Next Service Due', type: 'date', width: 'half' },
    { label: 'Findings / Observations', type: 'textarea', required: true },
    { label: 'Recommended Actions', type: 'textarea' },
    { label: 'Evidence Photos', type: 'photo', maxPhotos: 5 },
    { label: 'Inspector Signature', type: 'signature', required: true },
  ],
  '5': [ // Cleaning & Hygiene Log
    { label: 'Date', type: 'date', required: true, width: 'half' },
    { label: 'Time', type: 'time', required: true, width: 'half' },
    { label: 'Area / Location', type: 'text', required: true },
    { label: 'Cleaning Type', type: 'select', options: ['Routine', 'Deep Clean', 'Spot Clean', 'Sanitisation'], required: true },
    { label: 'Cleaner Name', type: 'text', required: true },
    { label: 'Floors Mopped', type: 'checkbox' },
    { label: 'Surfaces Wiped', type: 'checkbox' },
    { label: 'Bins Emptied', type: 'checkbox' },
    { label: 'Consumables Restocked', type: 'checkbox' },
    { label: 'Consumables Notes', type: 'textarea' },
    { label: 'Issues Found', type: 'textarea' },
    { label: 'Completion Photos', type: 'photo', maxPhotos: 5 },
    { label: 'Supervisor Check', type: 'checkbox' },
    { label: 'Cleaner Signature', type: 'signature', required: true },
    { label: 'Supervisor Signature', type: 'signature' },
  ],
  '6': [ // Access Control / Visitor Log
    { label: 'Date', type: 'date', required: true, width: 'half' },
    { label: 'Time In', type: 'time', required: true, width: 'half' },
    { label: 'Visitor Name', type: 'text', required: true },
    { label: 'Company / Organisation', type: 'text', required: true },
    { label: 'ID Type', type: 'select', options: ['ID Card', 'Passport', 'Driver\'s License', 'Other'], required: true, width: 'half' },
    { label: 'ID Number', type: 'text', required: true, width: 'half' },
    { label: 'Host Name', type: 'text', required: true },
    { label: 'Host Department', type: 'text', width: 'half' },
    { label: 'Host Contact', type: 'text', width: 'half' },
    { label: 'Purpose of Visit', type: 'textarea', required: true },
    { label: 'Badge Number Issued', type: 'text', required: true },
    { label: 'Time Out', type: 'time' },
    { label: 'Badge Returned', type: 'checkbox' },
    { label: 'ID Photo / Supporting Documents', type: 'photo', maxPhotos: 3 },
    { label: 'Visitor Signature', type: 'signature', required: true },
    { label: 'Security Officer', type: 'text', required: true },
  ],
  '7': [ // Work Order / Job Card
    { label: 'Work Order Number', type: 'text', required: true, width: 'half' },
    { label: 'Date Raised', type: 'date', required: true, width: 'half' },
    { label: 'Requested By', type: 'text', required: true },
    { label: 'Priority', type: 'select', options: ['Low', 'Medium', 'High', 'Emergency'], required: true },
    { label: 'Location', type: 'text', required: true },
    { label: 'Description of Work', type: 'textarea', required: true },
    { label: 'Assigned Vendor / Technician', type: 'text' },
    { label: 'Estimated Cost', type: 'text', width: 'half' },
    { label: 'Actual Cost', type: 'text', width: 'half' },
    { label: 'Start Date', type: 'date', width: 'half' },
    { label: 'Completion Date', type: 'date', width: 'half' },
    { label: 'Work Performed', type: 'textarea' },
    { label: 'Materials Used', type: 'textarea' },
    { label: 'Before / After Photos', type: 'photo', maxPhotos: 10 },
    { label: 'Completion Evidence Attached', type: 'checkbox' },
    { label: 'Technician Signature', type: 'signature' },
    { label: 'Approved By Signature', type: 'signature' },
  ],
  '8': [ // Incident / Near-miss Report
    { label: 'Date of Incident', type: 'date', required: true, width: 'half' },
    { label: 'Time of Incident', type: 'time', required: true, width: 'half' },
    { label: 'Location', type: 'text', required: true },
    { label: 'Incident Type', type: 'select', options: ['Injury', 'Near Miss', 'Property Damage', 'Environmental', 'Security'], required: true },
    { label: 'Severity', type: 'select', options: ['Minor', 'Moderate', 'Serious', 'Critical'], required: true },
    { label: 'Persons Involved', type: 'textarea', required: true },
    { label: 'Witnesses', type: 'textarea' },
    { label: 'Description of Incident', type: 'textarea', required: true },
    { label: 'Immediate Actions Taken', type: 'textarea', required: true },
    { label: 'Root Cause Analysis', type: 'textarea' },
    { label: 'Corrective Actions Required', type: 'textarea', required: true },
    { label: 'Incident Photos', type: 'photo', required: true, maxPhotos: 10 },
    { label: 'First Aid Administered', type: 'checkbox' },
    { label: 'Emergency Services Called', type: 'checkbox' },
    { label: 'Reporter Name', type: 'text', required: true },
    { label: 'Reporter Signature', type: 'signature', required: true },
    { label: 'Manager Review Signature', type: 'signature' },
  ],
  '9': [ // Evacuation Drill Record
    { label: 'Drill Date', type: 'date', required: true, width: 'half' },
    { label: 'Drill Time', type: 'time', required: true, width: 'half' },
    { label: 'Drill Type', type: 'select', options: ['Fire', 'Earthquake', 'Bomb Threat', 'General Emergency'], required: true },
    { label: 'Building / Zone', type: 'text', required: true },
    { label: 'Total Occupants', type: 'text', required: true, width: 'half' },
    { label: 'Evacuation Time (minutes)', type: 'text', required: true, width: 'half' },
    { label: 'Assembly Point Used', type: 'text', required: true },
    { label: 'All Areas Cleared', type: 'checkbox', required: true },
    { label: 'Roll Call Completed', type: 'checkbox', required: true },
    { label: 'Fire Wardens Present', type: 'textarea' },
    { label: 'Issues Identified', type: 'textarea' },
    { label: 'Lessons Learned', type: 'textarea' },
    { label: 'Recommendations', type: 'textarea' },
    { label: 'Drill Photos', type: 'photo', maxPhotos: 5 },
    { label: 'Drill Coordinator', type: 'text', required: true },
    { label: 'Coordinator Signature', type: 'signature', required: true },
  ],
  '10': [ // Permit to Work / Hot Work Permit
    { label: 'Permit Number', type: 'text', required: true, width: 'half' },
    { label: 'Date', type: 'date', required: true, width: 'half' },
    { label: 'Work Type', type: 'select', options: ['Hot Work', 'Confined Space', 'Working at Height', 'Electrical', 'Excavation'], required: true },
    { label: 'Location', type: 'text', required: true },
    { label: 'Contractor Name', type: 'text', required: true },
    { label: 'Company', type: 'text', required: true },
    { label: 'Description of Work', type: 'textarea', required: true },
    { label: 'Start Time', type: 'time', required: true, width: 'half' },
    { label: 'End Time', type: 'time', required: true, width: 'half' },
    { label: 'Hazards Identified', type: 'textarea', required: true },
    { label: 'Control Measures', type: 'textarea', required: true },
    { label: 'Fire Extinguisher Available', type: 'checkbox', required: true },
    { label: 'Fire Watch Required', type: 'checkbox' },
    { label: 'Area Isolated', type: 'checkbox' },
    { label: 'PPE Requirements', type: 'textarea', required: true },
    { label: 'Site Condition Photos', type: 'photo', maxPhotos: 5 },
    { label: 'Contractor Signature', type: 'signature', required: true },
    { label: 'Authorising Officer', type: 'text', required: true },
    { label: 'Authoriser Signature', type: 'signature', required: true },
    { label: 'Permit Closed', type: 'checkbox' },
    { label: 'Close-out Time', type: 'time' },
    { label: 'Close-out Signature', type: 'signature' },
  ],
  '11': [ // Certificate Register
    { label: 'Certificate Type', type: 'text', required: true },
    { label: 'Certificate Number', type: 'text', required: true },
    { label: 'Asset / Equipment', type: 'text', required: true },
    { label: 'Location', type: 'text', required: true },
    { label: 'Issuing Authority', type: 'text', required: true },
    { label: 'Issue Date', type: 'date', required: true, width: 'half' },
    { label: 'Expiry Date', type: 'date', required: true, width: 'half' },
    { label: 'Renewal Lead Time (days)', type: 'text', width: 'half' },
    { label: 'Responsible Person', type: 'text', required: true },
    { label: 'Renewal Status', type: 'select', options: ['Current', 'Due Soon', 'Expired', 'Renewed'], required: true },
    { label: 'Notes / Actions', type: 'textarea' },
    { label: 'Certificate Photos', type: 'photo', maxPhotos: 5 },
    { label: 'Document Attached', type: 'checkbox' },
  ],
  '12': [ // Pest Control & Waste Log
    { label: 'Date', type: 'date', required: true, width: 'half' },
    { label: 'Type', type: 'select', options: ['Pest Control', 'Waste Disposal', 'Hazardous Waste'], required: true, width: 'half' },
    { label: 'Location / Area', type: 'text', required: true },
    { label: 'Contractor / Company', type: 'text', required: true },
    { label: 'Technician Name', type: 'text', required: true },
    { label: 'Treatment / Service Type', type: 'textarea', required: true },
    { label: 'Chemicals / Materials Used', type: 'textarea' },
    { label: 'Quantity Disposed (if waste)', type: 'text' },
    { label: 'Disposal Method', type: 'text' },
    { label: 'Findings / Observations', type: 'textarea' },
    { label: 'Service Photos', type: 'photo', maxPhotos: 5 },
    { label: 'Follow-up Required', type: 'checkbox' },
    { label: 'Next Service Date', type: 'date' },
    { label: 'Technician Signature', type: 'signature', required: true },
    { label: 'FM Officer Signature', type: 'signature' },
  ],
  '13': [ // Parking & Vehicle Incident Log
    { label: 'Date', type: 'date', required: true, width: 'half' },
    { label: 'Time', type: 'time', required: true, width: 'half' },
    { label: 'Incident Type', type: 'select', options: ['Accident', 'Oil Spill', 'Unauthorised Parking', 'Tow Required', 'Vandalism', 'Other'], required: true },
    { label: 'Location / Bay Number', type: 'text', required: true },
    { label: 'Vehicle Registration', type: 'text', required: true },
    { label: 'Vehicle Make / Model', type: 'text' },
    { label: 'Owner / Driver Name', type: 'text' },
    { label: 'Contact Number', type: 'text' },
    { label: 'Description of Incident', type: 'textarea', required: true },
    { label: 'Actions Taken', type: 'textarea', required: true },
    { label: 'Tow Company Called', type: 'checkbox' },
    { label: 'Tow Company Name', type: 'text' },
    { label: 'Incident Photos', type: 'photo', maxPhotos: 5 },
    { label: 'Police Report Number', type: 'text' },
    { label: 'Reporting Officer', type: 'text', required: true },
    { label: 'Officer Signature', type: 'signature', required: true },
  ],
  '14': [ // Training & PPE Issuance Record
    { label: 'Date', type: 'date', required: true, width: 'half' },
    { label: 'Type', type: 'select', options: ['Training', 'PPE Issuance', 'Both'], required: true, width: 'half' },
    { label: 'Employee Name', type: 'text', required: true },
    { label: 'Employee ID', type: 'text', required: true, width: 'half' },
    { label: 'Department', type: 'text', width: 'half' },
    { label: 'Training Topic', type: 'text' },
    { label: 'Training Duration (hours)', type: 'text' },
    { label: 'Trainer Name', type: 'text' },
    { label: 'PPE Items Issued', type: 'textarea' },
    { label: 'PPE Size / Specifications', type: 'textarea' },
    { label: 'Training / PPE Photos', type: 'photo', maxPhotos: 5 },
    { label: 'Competency Assessment Passed', type: 'checkbox' },
    { label: 'Refresher Due Date', type: 'date' },
    { label: 'Employee Acknowledgement', type: 'checkbox', required: true },
    { label: 'Employee Signature', type: 'signature', required: true },
    { label: 'Issuing Officer', type: 'text', required: true },
    { label: 'Officer Signature', type: 'signature', required: true },
  ],
};
